name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - run: npm ci

    - name: empty build dir
      run: node .github/actions/empty-build-dir.js

    - run: npm run build --if-present

    - name: Commit & Push changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: github-actions[bot]@users.noreply.github.com
        message: 'Commit from GitHub Actions'
        add: '["./static/index.html", "./static/assets/*.*"]'
